### ISSUE TITLE
[Report] Go to next failure button

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#106]
**Is your feature request related to a problem? Please describe.**
When I analyse test failures I want to be able to go from one failed method to the next failed method with one click instead of navigating back and forth through the different views.

**Describe the solution you'd like**
A button like "go to next failed method" in the method screen of a failed method.

**Additional context**
Maybe this should be done with consideration to failure aspects either offering another button to go to the next failure aspect or only having a button for the next failure aspect.

**Comment by mreiche** [comment]
We could add 2 links for "goto next failed method" and "goto prev failed method" in the method details view, based on the "methodRunIndex".
