### ISSUE TITLE
[Report] Rename session tab to video tab

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#107]
**Is your feature request related to a problem? Please describe.**
When I first saw the session tab I was a bit confused what it's there for and where the video tab is. I rarely care about the session info and the video is what I'm interested in for test analysis.

**Describe the solution you'd like**
Either renaming the tab to "Video" or something like "Session recording" that makes it clear I can find the video there or split it in two tabs with one for the video and one for the session info.

**Additional context**
I don't remember ever using the session info for test analysis so far. I can only assume it's there to record which browser (+ version) was used.

**Comment by mreiche** [comment]
The session tab contains all session information, the video is just a part of it.
What disadvantage do you experience with that combination?

**Comment by sbke-mms** [comment]
One issue for me was, that I was very confused when there was no more video tab. The other thing is that for me the video is one of the most important parts when analysing failed tests while the other session info is unimportant to me in 99.9% of cases and just takes space away. Since this is a rather subjective issue, feel free to close it if you like.
