### ISSUE TITLE
need for isNotDisplayed() function

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra#108]
_isDisplayed()_ in _GuiElementCoreSequenceDecorator_ uses 1s sequence, which means that it takes always up to 1s to get _false_ as an expected result. 

In our tests I use it often to check if wait-spinners are hidden, we have up to 8 of them, so every check costs us up to 8s making our tests nearly 5 times slower in overall measurement.

Option 1: Pls. add _**isNotDisplayed()**_ function (or similar) that will end immediately if element is not displayed.

Option 2: Pls. add to all functions returning boolean value an _**boolean expectedResult**_ parameter (ideally as first one). If expected result is met, function should return immediately.

**Comment by mreiche** [comment]
Option 1: `asserts().assertIsNotDisplayed()`: https://docs.testerra.io/testerra/stable/index.html#_functional_asserts

Option 2: I don't unterstand this requirement, but Testerra 2 may fit your needs here by using `assert().display(boolean)`: https://docs.testerra.io/testerra/2.0-RC-11/index.html#_checks

**Comment by radzimir** [comment]
I could replace _isDisplayed()_ with _asserts().assertIsNotDisplayed()_ , it works better now.
