### ISSUE TITLE
isVisible(true) no returning result according to visibility

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#113]
I am on Testerra 1.6

**Describe the bug**
When I have a element in a modal window, nut sure if this is relevant, the element.isVisible(true) returns true even when the element is not fully visible.

**To Reproduce**
1. Go to some webpage that has a modal window
2. scroll inside the modal so that a button or something similar is only visible halfway

**Actual behavior**
element.isVisible(true) returns true
element.isVisible(false) returns true

**Expected behavior**
element.isVisible(true) returns false
element.isVisible(false) returns true

**Screenshots**
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/80685133/131128137-ca59e45e-4396-49e7-8067-54f4d777785c.png">

**Environment(please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 92

**Additional context**
The button click does not work until I manually scroll the element into place. I have tried many workarounds, nothing helps. I come to think that for Testerra, the button actually is visible because it see the entire content of the modal, but the user does not or something like that.

Also scrollIntoView() does not work, also scrolling down a bit did not work. 

Also just scrolling does not work:

JavascriptExecutor js = (JavascriptExecutor) driver;
js.executeScript(String.format("window.scrollBy(0,%s)", 20), "");

I solved it in a terrible way like that:

since I know I am just one TAB away from the button I need to press.

 Actions act = new Actions(driver);
 Action series = act.sendKeys(Keys.TAB).sendKeys(Keys.ENTER).build();
 series.perform();

**Comment by mreiche** [comment]
Can you provide example code (with URL) if possible?

**Comment by chrberSTO** [comment]
I do not have a public URL that I could share with you. We could however have a session and I can demonstrate the problem.

**Comment by chrberSTO** [comment]
This is just a comment for me, should we ever get to that so I know where to look for the problem in my code:

test_2505_mandatoryFields
SingleUseAddressDialoguePage --> public SingleUseAddressDialoguePage saveAddressWithError()
