### ISSUE TITLE
Checkou&Compile ends in "Could not find method install()"

### ISSUE THREAD

**Issue by erickubenka** [telekom/testerra#12]
**Describe the bug**
When checking out current `master` branch on a clean system and running `gradle clean compile` on project root directory an issue occurs.

**To Reproduce**
1. Checkout `master` branch of this project
2. Run `gradle clean compile` on it.

**Expected behavior**
Project compiles.

**Actual behavior**
````
E:\workspace\testerra>gradle clean compileJavaTest --stacktrace

FAILURE: Build failed with an exception.

* Where:
Script 'E:\workspace\testerra\publish.gradle' line: 28

* What went wrong:
A problem occurred evaluating script.
> Could not find method install() for arguments [publish_57ufhuqeyuu01v41ou65akukr$_run_closure2@1a099130] on root project 'testerra' of type org.gradle.api.Project.
````

**Screenshots**
*NONE*

**Test**
Not applicable

**Environment(please complete the following information):**
 - OS: Windows 10 Pro 20H2
- Gradle: 6.7
````
E:\workspace\testerra>gradle --version

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Windows 10 10.0 amd64
````
- JDK: openjdk 15.0.2 2021-01-19

````
E:\workspace\testerra>java --version
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

````

**Hardware (please complete the following information):**
(removed section)

**Additional context**
Reproduced on other System as well with 
````
openjdk 11.0.11-ea 2021-04-20
OpenJDK Runtime Environment (build 11.0.11-ea+4-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.11-ea+4-post-Debian-1, mixed mode, sharing)

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11-ea (Debian 11.0.11-ea+4-post-Debian-1)
OS:           Linux 5.10.0-4-amd64 amd64
````

Issue could be resolved, when applying java&maven gradle plugins before `publish.gradle` will be loaded
````
apply plugin: 'java'
apply plugin: 'maven'
// Do not move this integration because `group` and `version` is needed for publishing
apply from: rootProject.file('publish.gradle')
````

Best regards,
Eric

**Comment by martingrossmann** [comment]
I cannot reproduce this issue. Do you have a typo in your commands?

I tried the following with success:
`gradle clean compileJava`
`gradle clean compileTestJava` (not `compileJavaTest)`

**Comment by erickubenka** [comment]
Hmn. It comes up as well when just running `gradle clean compile`. But I already thought that it would hard to reproduce. But as it occured twice to me when running checkout&compile on different operating systems with different java and gradle versions let me think about a serious issue. 

May it's a gradle version related issue or something like that? 

The thing that it does not occur when changing the order of applying plugins confuses me. 

May I can reproduce it in a Docker container as well.

**Comment by erickubenka** [comment]
Hey,

thank you for your fast response, but the error occurs as well when running `gradle clean compileJava` or `gradle clean compile`. 
As it occurs twice to me using different operating systems with different gradle & java versions, this seems like a issue for me. 

May I'm able to reproduce it in a Docker container as well. I will try that tomorrow, because downgrading to Gradle 5.6.4 did not help either. 

The thing that everything works, when changing apply-order of Gradle plugins is confusing me. 

Best regards
Eric

**Comment by erickubenka** [comment]
Hey everyone, 

I was able to setup a simple Gradle 6.7.0 + JDK 15 container to reproduce this error. May this help to repdroduce it on your machines as well.

Dockerfile
````Dockerfile
FROM gradle:6.7.0-jdk15

RUN apt update && \
    apt install git

RUN git clone https://github.com/telekom/testerra.git
WORKDIR 'testerra/'

CMD ["bash"]
````

Commands to verify
````bash
# Build container
docker build . -t testerra/gradle:latest
# Run it and jump into bash of container
docker run -it testerra/gradle bash
# Run compile in /home/gradle/testerra
gradle clean compileJava
````

Best regards
Eric

**Comment by martingrossmann** [comment]
Hi Eric,

thank you for your help and your steps. I can reproduce this issue, but it does not depend on any Gradle or Java version. It's an issue of your `init.gradle`. ;-)

As a default _our_ `init.gradle` starts as follows:

`
allprojects {
    apply plugin: 'java'
    apply plugin: 'maven'
   ...
`

But of course, we cannot assume this as standard. I will fix this.

Regards
Martin

**Comment by erickubenka** [comment]
Ah. Great finding. And as I started with a plain operating system and configuration, there was no init.gradle at all. 
Thank you =)!
