### ISSUE TITLE
io.testerra.bup - forward username and password for proxy with username and password

### ISSUE THREAD

**Issue by jdoeschn** [telekom/testerra#140]
**Problem description**
I have to run testerra tests through an https proxy (so the system under test is behind this proxy). The proxy need s username and password for authentication. I need to provide username and password to the https proxy before accessing the SUT.

**Prefered solution*
On proxy setup, it should be possible to add credentials (username and passwort) for authentication against web proxies. 

**Describe alternatives you've considered**
I could setup browsermobproxy without testerra, but testerra already has a bup integration - so i'd prefere using it.

**Additional context**
no additional context.

Maybe it is enough to set in startServer method the parameters (if provided)
startServerUriBuilder.setParameter("proxyUsername", username);
startServerUriBuilder.setParameter("proxyPassword", password);
and add a way to set username and password

**Comment by JanDoeschner** [comment]
Thank you for the fast support! The bugfix solved my problem.
