### ISSUE TITLE
Report, failure aspects showing strange counts

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#147]
**Describe the bug**
The test report, failure aspects, shows wrong numbers of tests failed, skipped, passed

**To Reproduce**
1. Run test suite.
2. Look for failure aspects

**Expected behavior**
numbers shown in failure aspects should reflect what is shown under each aspect.

**Actual behavior**
Numbers in the failure aspects view differ from the aspect detail view

**Screenshots**

**Test**
If applicable, add a simple testcase to show us how to target the bug by code.

**Environment(please complete the following information):**
 - OS: TAP MMS
 - Browser Chrome
 - Testerra Version  1.6

**Additional context**
Overview:

![image](https://user-images.githubusercontent.com/80685133/139741652-3b9c80cf-b997-4393-a43d-b40e10b78a2d.png)

"Nullpointers" details:

![image](https://user-images.githubusercontent.com/80685133/139741754-4d974251-6ca0-48ef-8d63-2e087098e1c8.png)

"RuntimeException: Could not create instance of page class MyAccountModalPage" details view

![image](https://user-images.githubusercontent.com/80685133/139741877-b0d9cd1c-b796-42b2-b74d-f71775b86ec3.png)

**Comment by mreiche** [comment]
So you expect to see 49 failed tests for NPE instead of 21 and 15 failed RuntimeExceptions instead 8?
Can you enable "Show configuration methods" to see if this does the trick?

**Comment by chrberSTO** [comment]
Now, this I call instant respose, kudos.

Yes in fact that does the trick. Thank you. Maybe one could split configuration methods and normal methods on two sections and I would like them to be on by default, because most of the time, failed config methods, will kill your tests. But that might be different for others.

I wish you a good evening and thank you for the quick help.

**Comment by mreiche** [comment]
Usually, when only configuration methods fail, this switch will automatically turn on to show them.
Otherwise, you see failing configuration methods in the dependencies tab.
