### ISSUE TITLE
[Report] Fails validator: Add user hints to report

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#175]
Based on the changes of #172 and the new Fails validator a test with `@Fails` annoation could failed (and not Expected failed) if the validation fails.

The test automation experts should get a hint why the test is failed. At the moment the Report shows the `@Fails` annotation AND the `Failed` status:
![image](https://user-images.githubusercontent.com/22025965/142433495-79a20664-b4c9-4d47-8066-863d7674a748.png)

The user needs a short message like `Please check your Fails validator` or `Your conditions for Expected fails were not fulfilled`.

**Comment by sbke-mms** [comment]
@martingrossmann Do you have an example how it should look and how the corresponding code looks?

**Comment by martingrossmann** [comment]
I have no example but in case of a regular "Expected failed" additional information like the bug ticket are shown to the right of the tag:
![image](https://user-images.githubusercontent.com/22025965/175260343-2856e9cd-4c51-4092-9900-4ab9ca8b9a7a.png)

In case of using a validator and the validation check failed (a failed test is not "planned") the used validator and the message (see above) should places to the right of `@Fails`.
