### ISSUE TITLE
onMethodEnd: MethodContext.endTime is null

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#176]
**Describe the bug**
At the event `onMethodEnd` the attribute `MethodContext.endTime` is still null. Some test result sync tools like AzureDevOps connector are triggered by this event, but the cannot use this attribute.

**To Reproduce**
It was working with Testerra 1.8, because the call of  `methodContext.updateEndTimeRecursive(new Date())` was moved to `TestStatusController.finalizeMethod()`. This seems to be to late.

Can we move this call to `MethodContextUpdateWorker.onMethodEnd()`?

**Comment by martingrossmann** [comment]
Using the event `onTestStatusUpdate` should be a good alternative to get all needed information. But, it is very confusing to have the additional event `onMethodEnd` which does not have all final information.

**Comment by mreiche** [comment]
I see. Is it just the end time or anything else which is required?

**Comment by martingrossmann** [comment]
Yes. I changed the handling in Testerra Appium Connector (https://github.com/telekom/testerra-azure-devops-connector/pull/4) because only at `onTestStatusUpdate` I have the final test status like `Retried` or `Recovered`. At `onMethodEnd` it is not `Retried` but failed. 
And - for example - for syncing results is most cases there is no need to sync `Retried` methods, but of course _real_ failed method.

**Comment by mreiche** [comment]
So do you still think this is an issue or could it be closed?

**Comment by martingrossmann** [comment]
Well, what is better to use, what is best practice? At the moment `eu.tsystems.mms.tic.testframework.connectors.util.AbstractCommonSynchronizer` does not make sense.

**Comment by mreiche** [comment]
`AbstractCommonSynchronizer` is not used within Testerra, so its optional. I was invented before the event bus, so I guess its just outdated and should not be used anymore.

**Comment by mreiche** [comment]
I close this, because this is not an effective issue anymore. Using `TestStatusUpdateEvent` instead of `MethodEndEvent` is the key here.
