### ISSUE TITLE
Add additional information to report

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#179]
**Is your feature request related to a problem? Please describe.**
The Testerra legacy report provided the `ReportInfo` class to add some information to the dashboard or to method details page.
ReportNG does not have such a feature to personalize the report.

**Describe the solution you'd like**
The `ExecutionContext` could hold some meta data as a map. The content of this map can be placed on the dashboard in an extra box.

**Comment by mreiche** [comment]
We need to introduce a new `Info` model. My proposal would be to have the following information.

* Info Key (like `xray.sync.status`)
* Message
* LogLevel (like `WARN`, `INFO`, `ERROR`)

This Info model could be added to the `MethodContext` or `ExecutionContext` like:

```java
Info info = new Info("Synchronisation successful", LogLevel.INFO);
context.setInfo("xray.sync.status", info);
```

**Comment by martingrossmann** [comment]
If we add the `Info` object to `MethodContext` _and_ to `ExecutionContext` we will have the possibility to add information to the whole test run and to single methods.

**Comment by mreiche** [comment]
## Proposal 2: Add a `prompt` property to `LogMessage` class

A message with `prompt=true` is not a regular message based on a Log4J LogEvent, but it's user generated.

Advantages:
* We can reuse the `LogMessage` model
* LogMessages are context sensitive and can be placed in MethodContext or ExecutionContext
* They are visible in the reports log view
* They can be shown within the Reports' method details view by filtering:
  ```typescript
  const promptMessage = methodContext.logMessages.filter(value => value.prompt);
   ```

To create such a message programatically, do:

```java
LogMessage logMessage = new LogMessage("Synchronisation successful", Level.INFO);
methodContext.addLogMessage(logMessage);

Assert.assertTrue(logMessage.isPrompt());
```

Extend the `Loggable` interface.

```java
// Regular context sensitive log message
log().info("My log message");

// Prompt context sensitive log message
prompt().warn("XRay synchronisation failed");
```
