### ISSUE TITLE
Are there release notes or howtos, how to get from one release to the next?

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#186]
Hi there,

headline states it all. 

If so, where can I find them? Just reading the changeSet is not always clear for someone who does not develop the framework.
... or a diff in the documentation, so one does not have to read through all the documentation and spot the differences? Saying that, I could probably create a diff myself, but others might be interested in that as well.

Thanks and kind regards.
Christian

**Comment by chrberSTO** [comment]
One example that does not work anymore as it was removed:

ReportInfo.getRunInfo().addInfo()

but I have a hard time finding if this is gone for good or some alternativ mechanism can be used.
Where would I find what to do about it?

**Comment by mreiche** [comment]
This feature was undocumented for internal use only and gone with the old report module. But it's planned to have a new API for that here https://github.com/telekom/testerra/issues/179

**Comment by chrberSTO** [comment]
@mreiche but the example was just an example, the underlying question is:

Are there release notes or howtos, how to get from one release to the next?

Thanks.
Christian

**Comment by mreiche** [comment]
The only release notes we have are based on the tags. like https://github.com/telekom/testerra/releases/tag/1.11
Within v1 of Testerra, there are not big incompatibility changes planned that are part of the documentation at https://docs.testerra.io
For v2 of Testerra, we have an own article about that https://docs.testerra.io/testerra/2.0-RC-18/index.html#_migration_from_testerra_1
Otherwise we are keeping the API for documented features intact and remove them in further versions.

**Comment by chrberSTO** [comment]
One example would be to mention the deprecation of using the driver of the meta class, but to rather use this.getWebDriver(), which changed from earlier versions, maybe there are similar things that I do not know of or did not stumble across.

In general I would recommend that you make use of the @deprecated annotation in JavaDoc although I would prefer to have this inside the @Deprecated annotation, but Java people can not be convinced that this would make sense, as it looks

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6707041

I would love to have something like that
@Deprecated(description="Rather use the getter: this.getWebDriver() or the WebDriverManager.getWebDriver()")

But that does not exist, so JavaDoc it is.

Kind regards.
Christian

**Comment by chrberSTO** [comment]
Thank you

**Comment by chrberSTO** [comment]
By the way, how far along are you with v2, I am currently starting a new project, is 2.0 mature enough to be used in production?

**Comment by mreiche** [comment]
For this particular case, the variable is marked as deprecated and it works for us pretty well: https://github.com/telekom/testerra/blob/master/driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/AbstractPage.java#L52

Maybe this information is gone when you use binaries only.
