### ISSUE TITLE
WebDriverManager, Set DEFAULT_SESSION_KEY = <sessionKey> during test runtime

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#189]
**Is your feature request related to a problem? Please describe.**
I have a test, which uses two different WebDrivers, because these are two webpages, which interact, which is why I have to jump back and forth between both WebDrivers.

I have created a library of Elements, which I use, like lets say

```
public class Button extends GuiElement {

    public Button(WebDriver driver, String indentifier) {
        super(driver, By.xpath(String.format("//span[@id='%s']", indentifier))
    }

}

```
and a class UiElements, which gives me the Elements like so:

```
public class UiElements {
    public static Button button (String identifier) {
        return new Button(WebDriverManager.getWebDriver(), identifier);
    } 
}
```

This is because
```
UiElements.button("login");
```
reads better than
```
new Button(driver, "login");
```

because I can hide the driver part.

But when I want to switch drivers, the Button in UiElements is not found because this does not have the right driver, because it would have to read

```
public class UiElements {
    public static Button button (String sessionKey, String identifier) {
        return new Button(WebDriverManager.getWebDriver(sessionKey), identifier);
    } 
}
```

UiElements.button("session2", "login"); no longer reads so nicely, especially because there are hundreds in the pages.

**Describe the solution you'd like**
If I was able to set the DEFAULT_SESSION_KEY of the WebDriverManager, like: 

```
WebDriverManager.setDefaultSessionKey("session2"), which I would do in the test when switching back and forth between both web pages.

the WebDriverManager.getWebDriver() would automatically return the correct WebDriver and I could write:

setSession("session1")
MainPage s1_mainPage = loginPage.login("username", "password")
...

setSession("session2")
MainPage s2_mainPage = loginPage.login("username", "password")
...

setSession("session1")
```

**Describe alternatives you've considered**
Alternatively I could hand the right WebDriver while creating the page, which would have me creating WebDrivers in the test and pass them all the way through to the Button, which extends the GuiElement. This seems a lot of overhead, for such a switch.

**Additional context**
I have the problem that the test I am writing is really big and one would say, make it smaller, test individual pieces rather than the whole thing, but this is how it is, because I need the customer to see that this way the tests are nicer than what they did before.

```
WebDriver driverSession1 = WebDriverManager.getWebDriver("session1")

MainPage mainPage = loginPage.login(driver, "username", "password")
```

I also thought of writing my own CustomWebDriverManager which extends WebDriverManager and add a method, which allows me to do that, but the WebDriverManager is final. 
Then I though about creating a Testerra PR, but I wanted to discuss how to handle such cases before creating a useless pull request. I guess there are other issues, which I do not take into consideration, which maybe would prevent this from working.

I have solved the problem now, by setting the sessionKey inside my UiElements class

```java
public class UiElements {
    public static String sessionKey;

    public static Button button (String identifier) {
        return new Button(WebDriverManager.getWebDriver(sessionKey), identifier);
    } 
}
```

In the test I do
```java
UiElements.sessionKey = "session1"
MainPage s1_mainPage = loginPage.login("username", "password")
...

UiElements.sessionKey = "session2"
MainPage s2_mainPage = loginPage.login("username", "password")
...

setSession("session1")
```

**Comment by mreiche** [comment]
Note: Could you please format your code snippets please?

**Comment by mreiche** [comment]
Switching the WebDrivers this way should be prevented because of isolation reasons, especially in multi-threaded environments. The better approach would be, to create your elements from your page.

*Test*
```java
WebDriver session1 = WebDriverManager.getWebDriver("session1");
LoginPage loginPage1 = PageFactory.create(LoginPage.class, session1);
loginPage1.login("username", "password");

WebDriver session2 = WebDriverManager.getWebDriver("session2");
LoginPage loginPage2 = PageFactory.create(LoginPage.class, session2);
loginPage2.login("username", "password");
```

*LoginPage*
```java
class LoginPage {
    public void login(String username, String password) {
        Button loginButton = UiElements.button(this.getWebDriver(), "@id=loginBtn");
        loginButton.click();
    }
} 
```

**Comment by chrberSTO** [comment]
For whatever reason 
````
```java
````
 does not work

**Comment by martingrossmann** [comment]
You want to reduce the overhead by creating GuiElements, so is this a solution for you?

```
public class BasicPage extends Page

    ...
    protected GuiElement find(By by) {
        return new GuiElement(this.getWebDriver(), by); 
    }
    ...
}

public class MyPage extends BasicPage {

    private GuiElement button = find(By.xpath("//input"));

}
```

**Comment by mreiche** [comment]
I consider this question as answered.
