### ISSUE TITLE
Mail Connector - IMAP, POP3, SMTP - use of multiple propery files, multiple mail accounts

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#19]
Hi there,

the MailConnector http://docs.testerra.io/testerra/1.0-RC-23/#_mail_connector

has a property file that allows to specify the Mail account. 

1.) Can this propery file include more than one mail account? OK, I could use POP3 and IMAP in parallel, but this is not it.
2.) If not, can I have more than one property file? How could I reference them?
3.)In the ImapMailConnector, I see the reference to the property values and I could override the init method, but I am aksing myself if I am missing soemthing here and this is possible out of the box.

The use case is that the customer orders something and we check if the mail was received and then there is a sales rep, who also get an e-mail about the order, which we would also like to check.

Thanks.
Kind regards.
Christian

**Comment by mreiche** [comment]
You can try to set properties manually and the create a new instance of `ImapMailConnector` like

```java
PropertyManager.loadProperties("first-account.properties");
ImapMailConnector firstAccountConnector = new ImapMailConnector();
PropertyManager.loadProperties("second-account.properties");
ImapMailConnector secondAccountConnector = new ImapMailConnector();
```

**Comment by martingrossmann** [comment]
But the `mailconnection.properties` must remain complety empty. Otherwise the values of it overwrite your custom property files.

**Comment by martingrossmann** [comment]
@chrberSTO Does it solved your problem and can we close this issue?

**Comment by chrberSTO** [comment]
Have not had the time to check, yet. Thank you for the hint, I will check later. Please close.

 

From: Martin Großmann ***@***.***>
Reply to: telekom/testerra ***@***.***>
Date: Thursday, 22. April 2021 at 11:25
To: telekom/testerra ***@***.***>
Cc: chrberSTO ***@***.***>, Mention ***@***.***>
Subject: Re: [telekom/testerra] Mail Connector - IMAP, POP3, SMTP - use of multiple propery files, multiple mail accounts (#19)

 

@chrberSTO Does it solved your problem and can we close this issue?
