### ISSUE TITLE
Remove WebDriverMode.remote/local

### ISSUE THREAD

**Issue by mreiche** [telekom/testerra#190]
Do we need the property or configuration option for `WebDriverMode`?

`tt.webdriver.mode=remote` requires `tt.selenium.server.url`  to be defined. That means, the information if a remote or local session should be used is kind of redundant and maybe confusing.

My proposal is, to remove the property and just decide if a remote or local WebDriver session should be created based on the presense of a Selenium server URL.

`tt.selenium.server.url=` -> `local`
`tt.selenium.server.url=http://localhost:3124` -> `remote`

**Comment by martingrossmann** [comment]
If we remove the property we have to change the current handling of `tt.selenium.server.host`. 
Default value is always `localhost`. This allows to start your project with a very simple `test.properties` like here https://docs.testerra.io/testerra/stable/index.html#_create_test_properties.

For local webdriver mode also `tt.selenium.server.host` must be empty without default value.

This results in following presettings:
* `tt.selenium.server.url`: default `null`
* `tt.selenium.server.host`: default `null`

**For local mode:** Keep it empty, but define webdriver binary location (e.g. https://docs.testerra.io/testerra/stable/index.html#_create_a_local_session_not_recommended)

**For remote mode:** Fill out one of `tt.selenium.server.url` or `tt.selenium.server.host`:
```
tt.selenium.server.url=http://myserver:4444/wd/hub
# or
tt.selenium.server.host=localhost
```

`tt.selenium.server.port` can be left with default = 4444.

**Comment by mreiche** [comment]
Basically its `tt.selenium.server.url=http://§{tt.selenium.server.host}:${tt.selenium.server.port}`
