### ISSUE TITLE
Add Selenium platform support to tt.browser.setting

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#191]
**Is your feature request related to a problem? Please describe.**
In multi browser grids like Selenium Grid, Selenoid and the services Saucelabs, Browserstack and CrossBrowserTesting the platfom cabability is needed to deside wich OS you want to test. Only the selection of browser and browser version is no longer sufficient.

**Describe the solution you'd like**
At the moment you have to add manually the platform cap to browser options or to the global caps:

```java
// single browser options
options.setCapability(CapabilityType.PLATFORM_NAME, "WINDOWS");

// or
WebDriverManager.setGlobalExtraCapability(CapabilityType.PLATFORM_NAME, "WINDOWS");
```

**Describe alternatives you've considered**
The property `tt.browser.settings` should extended by a third part: `<browser>:<browserVersion>:<platform>`, e.g `firefox:90:WINDOWS`.

**Additional context**
* The platform part is optional and the default value is empty.
* If it is not set, no platform cap is created.
* The value is a string. You can use the Selenium `Platform` enum, but browser Services like Saucelabs need some more values.
* There are two capability types for platform: `platform` (deprecated) and `platformName`. Unfortunately the old `platform` is still used by some grids. The current usage should be:
  * Selenoid (GGR): `platformName`
  * Selenium 3 Grid: `platform`
  * Selenium 4 Grid: `platformName` 
  * Saucelabs: `platformName`
  * Browserstack: `platform`
  * CrossBrowserTesting: `platformName` 

We should setup both caps if a platform value is defined. It should verified against the grids to prevent incompatibilities.

Additional information:
* https://www.browserstack.com/docs/automate/selenium/select-browsers-and-devices#capability-override-rules
* https://support.smartbear.com/crossbrowsertesting/docs/automated-testing/frameworks/selenium/java.html
* https://www.selenium.dev/documentation/legacy/selenium_3/grid_setup/
* https://www.selenium.dev/documentation/grid/configuration/toml_options/
* https://docs.saucelabs.com/web-apps/automated-testing/selenium/
* https://aerokube.com/ggr/latest/#_creating_quota_files

**Comment by mreiche** [comment]
Two additional notes:

- We should also have a property named `tt.browser.platform`
- `WebDriverRequest` should also support `setPlatform()`

**Comment by martingrossmann** [comment]
One more note to Browserstack:
Browserstack defines some own caps like `os` and `os_version`. Furthermore it only accept some defined values for `platorm`.
If you want to use Browserstack you have to add such special caps manually.

(https://www.browserstack.com/docs/automate/selenium/select-browsers-and-devices#browserstack-specific-capabilities-mobile)
