### ISSUE TITLE
Raise language level to Java 11

### ISSUE THREAD

**Issue by mreiche** [telekom/testerra#194]
Many features, especially for the Lists, Streams and Optionals are only available in Java > 8. I would like to raise the default language level to Java 11 then.

*build.gradle*
```groovy
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_1_8
```

What you think?

**Comment by martingrossmann** [comment]
Is this safe to create Java 8 binaries based on Java 11 sources?

I found different meanings:
* https://stackoverflow.com/questions/54447541/how-to-produce-code-in-java-11-but-target-java-8-and-above/54447780
* https://discuss.gradle.org/t/compile-with-java-11-to-java-8-language-level/39123/4

**Comment by mreiche** [comment]
Well, I prefer to raise the JRE to 11 as well.

**Comment by martingrossmann** [comment]
Short note: TestNG 7.6 requires JDK 11 as minimum JDK
https://github.com/cbeust/testng/issues/2637

**Comment by martingrossmann** [comment]
TestNG 7.6 fixes a bug with skipped configuration methods. With TestNG < 7.6 skipped configuration methods have the status `NO_RUN`
https://github.com/cbeust/testng/issues/2729
