### ISSUE TITLE
PageFactory->create(...) failing after 20 calls

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra#201]
**Describe the bug**

eu.tsystems.mms.tic.testframework.pageobjects.factory.PageFactory->create(...) fails after 20 calls.

This is caused by private static counter-variable LOOP_DETECTION_LOGGER that never get resetet back to 0.

**To Reproduce**
1. Make a test calling PageFactory->create(...) in a loop.

**Expected behavior**
It should be posible to instatiate infinitie number of pages in a test.

**Actual behavior**
Runtime Exception with message "PageFactory create loop detected loading" is flying.

**Workaround**
Set _tt.page.factory.loops_ to some very big number you never exeed in your test.

**Comment by martingrossmann** [comment]
Hi,

thank you for that issue, we look into it.

**Comment by martingrossmann** [comment]
@radzimir I made a PR with improved handling of that PageFactory buffer. Now there is a reset of that buffer after every test. This could help in case of dataprovider tests.

Within a test there is still the limit of 20 page creations in a row to prevent for unchecked page instantiations. If you need a higher limit you have to use the known property.
