### ISSUE TITLE
Exception in dataprovider occours undefined status in test method

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#214]
**Describe the bug**

If an assertion or exception occurs in a dataprovider method, TestNG will skip the following test step. But Testerra has different test results in Execution context and in ReportNG

**To Reproduce**

Both test methods will skipped because of failed dataprovider methods:

```java
@DataProvider(name = "dpAssertFailed")
public Object[][] dpAssertFailed() {
      Object[][] objects = new Object[1][1];
      Assert.fail("Failed assertion in Dataprovider");
      return objects;
}

@Test(dataProvider = "dpAssertFailed")
public void testDpAssertFailed(String dp) throws Exception {
}

@DataProvider(name = "dpException")
public Object[][] dpExecption() {
      throw new RuntimeException("Exception in Dataprovider");
}

@Test(dataProvider = "dpException")
public void testDpException(String dp) throws Exception {
}
```

The execution context has no clear result:
![image](https://user-images.githubusercontent.com/22025965/157698554-f0c6a85d-6a02-4316-91a2-dce94667f8fd.png)

ReportNG shows both test methods as failed with no end date (unfinished method contexgt):
![image](https://user-images.githubusercontent.com/22025965/157699586-a60ffe44-7cf0-494e-a363-31f5730c9856.png)

**Expected behavior**

TestNG handles the status correctly as skipped:
![image](https://user-images.githubusercontent.com/22025965/157698402-431fc82e-9a1f-48c2-ae46-4513928ef231.png)

**Environment(please complete the following information):**
 - Version: Testerra master

**Comment by mreiche** [comment]
This is true, but its not a bug, because the dataprovider errors are handled as real errors in https://github.com/telekom/testerra/blob/master/core/src/main/java/eu/tsystems/mms/tic/testframework/report/TesterraListener.java#L526

In TestNG, a dataprovider method will not result in a Testerra MethodContext, so the original TestNG method will be `skipped` but the Testerra MethodContext will be `failed`. This is not really a bug but a wanted behaviour. Maybe, we could tell TestNG to mark this method as `failed` as well.

**Comment by martingrossmann** [comment]
Yes, Testerra creates only a method context if a data provider failed.

But there is a bug because Testerra does not handle that case correctly. Testerra knows the two method contexts but the status is missing (see screenshot of log, there is something missing).

I fixed that with linked PR. The result of the same execution looks as follows:
![image](https://user-images.githubusercontent.com/22025965/157878101-d0224cc7-cd4b-4e2d-a772-04cbe883802f.png)

TestNG set the test method status to skipped so I also set it in the `MethodContext`.

**Comment by martingrossmann** [comment]
> When the MethodContext status is not known, one should debug whats happing in `pAfterInvocation` and if a `TestStatusUpdateEvent` gets fired for this method.

Before no `TestStatusUpdateEvent` was fired. After my fix it is triggerd and can finalize the method context.
