### ISSUE TITLE
[Report] Check `virtual-log-view` vs. `log-view` vs. AbstractLogView

### ISSUE THREAD

**Issue by Zsar** [telekom/testerra#245]
- Class `logs` can probably be pulled into the templates, so it cannot be forgotten in the future (c.p. #217 ).
- VirtualLogView is "strictly more" than LogView, so we can probably compose it _out of_ "LogView plus extras" and drop some code on the way.

**Comment by martingrossmann** [comment]
From my point this issue not more relevant.
