### ISSUE TITLE
Library of standard HTML5, HTML elements

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#26]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Library of standard elements.
Standard Elements, 
e.g. Dropdown Field with methods for selection of elements in a dropdown, etc.
Table, with table lines and values of each columns in the line.

DropDownGuiElement ddGuiElement = new DropDownGuiElement(By by)
ddGuiElement.selectEntry(String name)

**Describe alternatives you've considered**
Create this element myself and reuse it throughout the project.

**Additional context**

**Comment by mreiche** [comment]
We are planning to create a library of application related components for SalesForce, Drupal etc. Feel free to create your own library project and share it with us. But they are not and will never be part of the core.
