### ISSUE TITLE
filtering logs is not reliable

### ISSUE THREAD

**Issue by marc2202** [telekom/testerra#262]
Filtering on logs page is very difficulty. The search does not target the whole log-report.
Example log line:
09:48:49.551 [TestNG-test=Failed Status Creator-1] [INFO]: MethodStartWorker - 
Run Test(io.testerra.report.test.pretest_status.simple.GenerateFailedStatusInTesterraReportTest.testAssertCollector)
 - filtering is just possible for content in the 2nd row in general
 - "Run Test(io"  won't be applied "(" ==> need to replace "(" with "."
 - same for searches with ")"

1. open Testerra Report
2. click 'Logs' on sidebar
3. try to search for different content ==> "09:48:49.551", " MethodStartWorker", "Run Test(io", "AssertCollector)"

**Expected behavior**
Filter terms are marked all over the logs report

**Actual behavior**
Non of the given filter examples will be marked in the logs report

**Environment(please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 104

**Hardware (please complete the following information):**
 - Device: ThinkPad
 - OS: Window (10)
 - Browser: chrome
 - Version: 104

**Additional context**
![parentheses_filter_issue](https://user-images.githubusercontent.com/73551235/186127295-2a53b775-a451-45e6-87df-96633bb1ce87.png)
![time_filter_issue](https://user-images.githubusercontent.com/73551235/186127300-0074351f-b983-46c9-9385-f9422fad1392.png)

**Comment by mreiche** [comment]
Maybe the input string is not masked for use in regular expressions.
