### ISSUE TITLE
Get access to elements outside of a component

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#265]
**Is your feature request related to a problem? Please describe.**
When I work with components I sometimes have to interact with elements that are outside of the component in the DOM while they logically belong to the component. The `find()` method inside the component only finds child elements of the component. I need a way to access elements that aren't child elements of the component.

**Describe the solution you'd like**
A method for components to find elements outside of them (in regards to the DOM structure). 

**Describe alternatives you've considered**

**Additional context**
Currently the following code is used as a workaround. Via the `body` attribute we can access elements outside of the current `container`.
```
protected final UiElement body;
public OwnComponent(UiElement container) {
        super(container);
        AtomicReference<UiElement> atomicReference = new AtomicReference<>(container);
        container.traceAncestors(nameable -> {
            if (nameable instanceof UiElement) {
                atomicReference.set((UiElement) nameable);
                return false;
            } else {
                return true;
            }
        });

        body = atomicReference.get();
}
```

**Comment by mreiche** [comment]
You can implement the `UiElementFinderFactoryProvider` interface and pass the `rootElement.getWebDriver()` to access the document root: https://docs.testerra.io/testerra/stable/index.html#_implement_uielementfinder

**Comment by mreiche** [comment]
To be more precise. Because this feature request is still unmaintained.
```java
private final UiElement body;
public OwnComponent(UiElement container) {
        super(container);
        UiElementFinder finder = UI_ELEMENT_FINDER_FACTORY.createFinder(container.getWebDriver());
        body = finder.find(By.tagName("body"));
}
```

**Comment by martingrossmann** [comment]
Thanks for the code snipped. This would be the simpliest solution. I will add an example to the documentation.

But the new elements have no parent. It would be nice if the my elements have as parent my component.
Background: Some website components add dynamically elments which are outside from my root element, but they belong to the website component.

**Comment by martingrossmann** [comment]
> Thanks for the code snipped. This would be the simpliest solution. I will add an example to the documentation.
> 
> But the new elements have no parent. It would be nice if the my elements have as parent my component. Background: Some website components add dynamically elments which are outside from my root element, but they belong to the website component.

I answered that by myself. I updated the PR with a new solution.
https://github.com/telekom/testerra/blob/feature/doc-update-components/docs/src/docs/pageobject/components.adoc#break-out-from-components
