### ISSUE TITLE
When using CONTROL.collectAssertions() I want a screenshot for every failed assertion that occured

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#272]
**Is your feature request related to a problem? Please describe.**
When a test fails within a `collectAssertions()` I currently only get a screenshot at the end of a test. A screenshot for every individual fail would be much more helpful for test analysis.

**Describe the solution you'd like**
Preferably a screenshot for every fails that happens in a test even if it is within a `collectAssertions()`.

**Describe alternatives you've considered**
A minimal solution would be a screenshot for every `collectAssertions()` that fails in a test.

**Comment by mreiche** [comment]
Should be easy to implement since Testerra's data model supports *n* assertions per test.
