### ISSUE TITLE
ScrolltoTop with offset support

### ISSUE THREAD

**Issue by MartinTzschoppeMMS** [telekom/testerra#274]
I would like to see an UiElement.scrolltoTop() function with an Offset Parameter to allow positioning an element right beneath a sticky header, e.g for layout tests.

**Comment by mreiche** [comment]
When the overlapping header is an element, you can just use `header.scrollIntoView(new Point(0,0))`

**Comment by MartinTzschoppeMMS** [comment]
_scrollIntoView(new Point(0,0))_ aligns an element to the center of the screen. For a layout test e.g of a large table, the created screenshot will be cutted, if the table is larger than half of the screen. I can't use _scrollToTop_ on the table element because its aligns on the top of the screen and there is a sticky header. This header is always displayed, when i scroll up and down.

So i need a _scrollToTop_ with offset parameter to scroll through the content and align the table right beneath the sticky header (size of the header element would be my offset for the scrollToTop command) , or in short in pseudo code:
`largeTable.scrollToTop(stickyheader.ySize)`

**Comment by MartinTzschoppeMMS** [comment]
That's a point. Thanks for the help. i will close this issue and use `scrollIntoView` with an offset.
