### ISSUE TITLE
Take screanshot on failed assertions inside `CONTROL.collectAssertions()`

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#281]
**Is your feature request related to a problem? Please describe.**
When a test with `CONTROL.collectAssertions()` fails I only see the screenshot of the end of the test so I don't know how the website looked when the failure occured.

**Describe the solution you'd like**
Add a screenshot for each failed assertion insided `CONTROL.collectAssertions()` to the steps view so it's easier to analyze the failure.

**Describe alternatives you've considered**
I could add `UITestUtils.takeScreenshot(this.getWebDriver(), true);` before every assertion by hand buy depending on the amount of assertions I have it could be rather cumbersome and would also add screenshots when the assertion doesn't fail.

**Comment by martingrossmann** [comment]
@sbke-mms This is a duplicate of #272. Which one can be closed?

**Comment by sbke-mms** [comment]
Duplicate of #272
