### ISSUE TITLE
Request capabilities does not overwrite global browser capabilites

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#285]
**Describe the bug**
You can define caps for your `DesktopWebDriverRequest` by setting

```java
DesktopWebDriverRequest request = new DesktopWebDriverRequest();
request.getDesiredCapabilities().setCapability(CapabilityType.PROXY, proxy);
```

This does not overwrite existing caps if a proxy cap is set by 

```java
WEB_DRIVER_MANAGER.setUserAgentConfig(Browsers.chrome, new ChromeConfig() {
    @Override
    public void configure(ChromeOptions options) {
        options.setProxy(defaultProxy);
    }
});
```

**Expected behavior**
The proxy caps setting from the request should overwrite the global browser caps, but ...

**Actual behavior**
... it does not.

**Comment by martingrossmann** [comment]
This is fixed with Selenium 4 branch. In Selenium 4 the destination capability container for creating a new session is browser option object. 
All caps are merged into browser options (https://github.com/telekom/testerra/blob/fc8e57387a960b271d1318f97a5edaf6d0a05831/driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java#L178)

The `merge` method was update in Selenium 4, so no browser specific caps are lost any more. --> Cannot fixed with Selenium 3.

**Comment by mreiche** [comment]
This is original Testerra 1 behaviour, where *global capabilities* are built into the capabilities very last. I think the reason was the Selenoid grid plugin integration (video support).
Changing this may break backwards compatibility.

**Comment by martingrossmann** [comment]
The _global capabilities_ are deprecated. The plan is to remove that feature. We only should have for configuration that order
1. `test.properties`
2. `WEB_DRIVER_MANAGER.setUserAgentConfig`
3. `DesktopWebDriverRequest`

But removing the _globals_ has no impact to Selenoid connector. I have to change the merging of Selenoid caps in https://github.com/telekom/testerra-selenoid-connector/blob/cfb79e8d9f872ddb9106cdf52d4e849aa5168a07/src/main/java/eu/tsystems/mms/tic/testerra/plugins/selenoid/webdriver/SelenoidCapabilityProvider.java#L58 like I have done for the old global caps: https://github.com/telekom/testerra/blob/01db43af1f61b171b1b93cee813484387378be6e/driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverCapabilities.java#L96.

BTW there is also a merge issue in Selenium 3 which cannot handle caps like `ChromeOptions`, but Selenium 4 can. So I want to change this behaviour with Selenium 4 (#292)
