### ISSUE TITLE
Allow case-insensitive text comparison for UiElements

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#295]
**Is your feature request related to a problem? Please describe.**
The same text might be displayed with different capitalization at different places of an application. If I want to compare them for their "content" but not their capitalization it would be good to do so via a testerra function.

**Describe the solution you'd like**
Either add a parameter to existing functions for text/value comparrison or add a new function that ignores capitalization when comparing values.

**Describe alternatives you've considered**
Get the actual values and make them lower case and compare them with Assert.equals. 

**Additional context**

**Comment by sbke-mms** [comment]
This can be already done with the `matches(String)` functionality of testerra. Documentation is incomplete here and should be added.

**Comment by martingrossmann** [comment]
Regarding the last comment I close this issue with "won't fix".
