### ISSUE TITLE
Gradle 7.0 Source Code Support

### ISSUE THREAD

**Issue by erickubenka** [telekom/testerra#32]
**Is your feature request related to a problem? Please describe.**
As working with Gradle 7.0 checkout&compile of this project/repository won't work anymore, because several `build.gradle` files using deprecated keywords like `compile` or `testCompile`.
These keywords were replaced by `api` / `implementation` or even `testImplemenation`.
See https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal 

**Describe the solution you'd like**
I would like to rewirte the `build.gradle` files to use the new replacements of deprecated and removed keywords.

**Describe alternatives you've considered**
Using Gradle version < 7.0

**Additional context**
Nothing to add.

Please let me know, if I can just go ahead and create a pull request.

**Comment by mreiche** [comment]
What would be the way to do a upward-compatbile change to our source code?

* For me, `api` is not supported for Gradle 6.6: `Could not find method api() for arguments [io.testerra:core:1.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`
* What is the equivalent for `compileOnly`?
* Please feel free to open a PR.

**Comment by mreiche** [comment]
What I found out:

* To support `api` instead of `compile`, you have to change
    ```groovy
    // apply plugin: 'java'
    apply plugin: 'java-library'
    ```

* `compileOnly` is not deprecated
* `apply plugin: 'maven'` is deprecated which has been replaced by `maven-publish`, but our `publish.gradle` is incompatible.
    ```
    Could not find method install() for arguments
    ```
    @martingrossmann

**Comment by martingrossmann** [comment]
I confirm with that to clean our gradle files. At the moment we have a mix of old and new Gradle features.

As a minimum Gradle version we should use Gradle 6. IMHO it's the most used version.
