### ISSUE TITLE
Update Protobuf library

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#333]
**Is your feature request related to a problem? Please describe.**
In .proto files fields are frequently marked "[deprecated=true]". When generating bindings, in `*.ts` files the markers about deprecated fields are missing. The current used lib `protobufjs` cannot handle it.

**Describe the solution you'd like**
Use the lib `ts-proto`

**Additional context**
There is no comment of any contributor on https://github.com/protobufjs/protobuf.js/issues/1560.

**Comment by conradstrassburger** [comment]
Claiming this.
