### ISSUE TITLE
`TestClassContext` annotation creates additional class context with empty method context

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#44]
**Describe the bug**
Using the annotation `TestClassContext` and in case of failing test methods the current `ClassContext` is added twice to `TestContext`.
One of these `ClassContexts` contains an empty `MethodContext`. This results in the report like this:

![image](https://user-images.githubusercontent.com/22025965/117008095-a70e7780-acea-11eb-959b-2b8836525042.png)

Method details:
![image](https://user-images.githubusercontent.com/22025965/117008250-d02f0800-acea-11eb-9fed-45e5b5c0749c.png)

**To Reproduce**
Execute this simple test case. The custom event listener will log `tests.DemoTest - Count class context: 2`.

* If you remove `@TestClassContext`, you only get 1 `ClassContext` _or_
* If you remove the `Assert`, you only get 1 `ClassContext`.

````java
@TestClassContext(name = "MyClassContext")
public class DemoTest extends TesterraTest implements Loggable {

    @Test
    public void testFailing() {

        TesterraListener.getEventBus().register(new ExecutionFinishEvent.Listener() {
            @Override
            @Subscribe
            public void onExecutionFinish(ExecutionFinishEvent event) {

                List<ClassContext> list = ExecutionContextController.getCurrentExecutionContext()
                        .readSuiteContexts()
                        .flatMap(SuiteContext::readTestContexts)
                        .flatMap(TestContext::readClassContexts)
                        .collect(Collectors.toList());
                log().info("Count class context: " + list.size());
            }
        });

        Assert.assertEquals(1, 2);
    }

}
````

**Expected behavior**
The current `ClassContext` must not double in current `TestContext`

**Comment by mreiche** [comment]
Do you have the legacy `report` module activated?

**Comment by martingrossmann** [comment]
No, only `report-ng` is active.
