### ISSUE TITLE
one log pro test-class

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra#47]
It would be nice to have one log per one runnung thread/test-class, if possible.

Log files could be then linked in Dasboard's 'Test Classes' table.

**Comment by mreiche** [comment]
I guess this has been fixed recently: https://github.com/telekom/testerra/pull/43

**Comment by martingrossmann** [comment]
@radzimir #43 was part of Testerra release 1.1. Please verify your issue, so we can close it.
