### ISSUE TITLE
no exception if Locate->unique() constraint was not fulfilled

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra#49]
In Example like that:

```
            GuiElement sectionEl = container.getSubElement( Locate.by( By.xpath(section.getXPath() ) ).unique() );
            int sectionElCnt = sectionEl.getNumberOfFoundElements();
```

if section.getXPath() selects 2 elements, then creation of GuiElement ends without exception, then getNumberOfFoundElements returns 0.

I would expect, that getNumberOfFoundElements should throw some Exception to catch the constraint violation early. 

Internally, DesktopGuiElementCore->find() throws an exception but it gets consumed in isPresent() turning into assumption that element wasn't found.

**Comment by mreiche** [comment]
`getNumberOfFoundElements()` or `isPresent()` wont throw any exceptions.

It would be a bug, when the given xPath returns actual 0 but `getNumberOfFoundElements()` return 0.
