### ISSUE TITLE
[Report] Classes overview on dashboard contains '0' digits

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#57]
**Describe the bug**
Since TT 1.2 the classes view on dashboard contains little digits '0' within the bar chart.

![image](https://user-images.githubusercontent.com/22025965/120802254-84b68680-c542-11eb-988d-cbe28550cbc4.png)

**Environment**
 - Testerra 1.2 - ReportNG

**Comment by mreiche** [comment]
Can you confirm that this is only testerra2 related?

**Comment by martingrossmann** [comment]
I mean Testerra 1.2, not TT 2.

**Comment by mreiche** [comment]
Has something todo with the build on deploy pipeline. Local builds are just fine.

**Comment by martingrossmann** [comment]
Linux vs. Windows? Well, in Testerra 1.1 there were no digits. Could it be to do with visibility of status on dashboard?

**Comment by mreiche** [comment]
The ApexChart when building the pipeline is newer than in my local dev environment. It shows now series with 0 elements.
