### ISSUE TITLE
Internet Explorer isn't starting on SeleniumHub on Testerra v.  2.0-RC-7

### ISSUE THREAD

**Issue by fdomesle** [telekom/testerra#70]
**Describe the bug**
If I try to exec `final WebDriver driver = WEB_DRIVER_MANAGER.getWebDriver();` with test.properties `tt.browser.setting= ie:11`
(the request isn't even showing up on my SeleniumHub, with Safari e.g. it's working)

**Expected behavior**
The internet explorer starts on my SeleniumHub Server. (With plain Selenium it's working)

**Environment(please complete the following information):**
 - OS: [WIN 10]
 - Browser [internet explorer]
 - Version [11]

You are welcome to contact me directly.
 
![image](https://user-images.githubusercontent.com/82835456/122088740-54a29980-ce06-11eb-912c-756981c172db.png)
![image](https://user-images.githubusercontent.com/82835456/122088774-5ec49800-ce06-11eb-894f-8f667c714ca9.png)
![image](https://user-images.githubusercontent.com/82835456/122088999-9af7f880-ce06-11eb-80bb-a141f5b88b5b.png)

**Comment by martingrossmann** [comment]
@fdomesle Which Selenium version are you using? Its 3.14 or 4.x?

**Comment by fdomesle** [comment]
@martingrossmann 3.141.59
