### ISSUE TITLE
[Report] Dependency tree does not shown dependsOnGroup methods

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#72]
**Describe the bug**
The dependecy tree in method details shows dependened test and setup methods. The dependency of test methods can done with TestNG attributes `dependsOnMethod` and `dependsOnGroup`.
In case of `dependsOnGroup` the methods are missing in the tree.

**To Reproduce**
Two test methods are linked via `dependsOnGroup`
```java
@Test(groups = "myGroup")
public void test01() {
}

@Test(dependsOnGroups = "myGroup")
public void test02() {
}
```

In report the dependency tree of `test02` does not contain the method `test01`.

**Environment(please complete the following information):**
 - Testerra 1.3

**Comment by mreiche** [comment]
May be related to #177

**Comment by martingrossmann** [comment]
Not really. This bug describes the visualization in the report. Here I asume the TestNG config is fine but Testerra cannot show all dependencies.
