### ISSUE TITLE
Missing frame switch in DesktopWebDriverUtils

### ISSUE THREAD

**Issue by gehtsoklar** [telekom/testerra#93]
**Describe the bug**
I am trying to use clickJS from DesktopWebDriverUtils to click an element inside a frame.
The element is defined as GuiElement inside the frame-element and is found.
When passing the GuiElement to clickJS, an 'utils.JSUtils - Error executing script' occurs, it throws a StaleElementReferenceException.
Looks like the method accesses the WebElement without frame switching.

**Expected behavior**
clickJS works for elements with frameLogic as well as without frameLogic

**Comment by mreiche** [comment]
Note: This is already fixed in Testerra 2, because switching frames is implemented internally in `findWebElement()`
